export const THEMES = [
  // ─── Automático ───────────────────────────────────────────────
  {
    id: "system",
    title: "Automático",
    subtitle: "Sistema Operacional",
    desc: "Acompanha o modo claro ou escuro configurado no seu sistema",
    icon: "brightness_auto",
    category: "auto",
    isDark: null,
    colors: ["#3b82f6", "#64748b", "#f1f5f9"],
  },

  // ─── Temas Claros (Light) ──────────────────────────────────────
  {
    id: "light",
    title: "Clean Pearl",
    subtitle: "Claro Minimalista",
    desc: "Visual nítido, arejado e sem distrações para estudos diurnos",
    icon: "light_mode",
    category: "light",
    isDark: false,
    colors: ["#091426", "#ffffff", "#f7f9fb"],
  },
  {
    id: "catppuccin-latte",
    title: "Catppuccin Latte",
    subtitle: "Pastel & Lavanda",
    desc: "Tema claro suave e relaxante em tons pastéis aconchegantes",
    icon: "pets",
    category: "light",
    isDark: false,
    colors: ["#8839ef", "#eff1f5", "#1e66f5"],
  },
  {
    id: "rose-pine-dawn",
    title: "Rosé Pine Dawn",
    subtitle: "Linho & Rosé",
    desc: "Paleta elegante em tons de linho natural, rosa desértico e dourado",
    icon: "spa",
    category: "light",
    isDark: false,
    colors: ["#d7827e", "#faf4ed", "#907aa9"],
  },
  {
    id: "matcha-latte",
    title: "Matcha Latte",
    subtitle: "Chá Verde Claro",
    desc: "Verde menta claro e sálvia calmante para sessões longas de leitura",
    icon: "park",
    category: "light",
    isDark: false,
    colors: ["#2d6a4f", "#f2f7f4", "#52b788"],
  },
  {
    id: "nord-light",
    title: "Nordic Snow",
    subtitle: "Aurora Polar",
    desc: "Inspirado na neve ártica e tons gélidos de azul e ardósia clara",
    icon: "ac_unit",
    category: "light",
    isDark: false,
    colors: ["#5e81ac", "#eceff4", "#88c0d0"],
  },
  {
    id: "tokyo-day",
    title: "Tokyo Day",
    subtitle: "Sakura Blossom",
    desc: "Visual moderno inspirado na flor de cerejeira e primavera japonesa",
    icon: "local_florist",
    category: "light",
    isDark: false,
    colors: ["#3d59a1", "#f7f7fa", "#f07178"],
  },
  {
    id: "ocean-breeze",
    title: "Ocean Breeze",
    subtitle: "Azul Celeste",
    desc: "Tons de brisa marítima e céu limpo para refrescar o ambiente de foco",
    icon: "water",
    category: "light",
    isDark: false,
    colors: ["#0284c7", "#f0f8ff", "#38bdf8"],
  },
  {
    id: "solarized-light",
    title: "Solarized Light",
    subtitle: "Precisão & Ocre",
    desc: "Célebre paleta de legibilidade científica com fundo marfim suave",
    icon: "wb_sunny",
    category: "light",
    isDark: false,
    colors: ["#268bd2", "#fdf6e3", "#b58900"],
  },
  {
    id: "warm-sepia",
    title: "Café & Paper",
    subtitle: "Sépia Acolhedor",
    desc: "Tons quentes de papel envelhecido e café para leitura confortável",
    icon: "local_cafe",
    category: "light",
    isDark: false,
    colors: ["#c86432", "#fdfbf7", "#4a3b32"],
  },

  // ─── Temas Escuros (Dark) ──────────────────────────────────────
  {
    id: "dark",
    title: "Slate Obsidian",
    subtitle: "Escuro Clássico",
    desc: "Grafite e ardósia ergonômico para longas sessões de foco",
    icon: "dark_mode",
    category: "dark",
    isDark: true,
    colors: ["#d0ceca", "#202125", "#17181b"],
  },
  {
    id: "midnight-oled",
    title: "Midnight OLED",
    subtitle: "Preto Absoluto",
    desc: "Preto 100% puro (#000) e azul elétrico para telas AMOLED e imersão total",
    icon: "nightlight_round",
    category: "dark",
    isDark: true,
    colors: ["#60a5fa", "#000000", "#0a0a0c"],
  },
  {
    id: "dracula",
    title: "Dracula Studio",
    subtitle: "Vampire Violet",
    desc: "Fundo roxo escuro consagrado com acentos em lilás, ciano e verde neon",
    icon: "auto_awesome",
    category: "dark",
    isDark: true,
    colors: ["#bd93f9", "#282a36", "#8be9fd"],
  },
  {
    id: "catppuccin-mocha",
    title: "Catppuccin Mocha",
    subtitle: "Pastel Lavanda",
    desc: "Paleta aconchegante e sofisticada em tons pastel escuros e lavanda",
    icon: "pets",
    category: "dark",
    isDark: true,
    colors: ["#cba6f7", "#1e1e2e", "#89b4fa"],
  },
  {
    id: "tokyo-night",
    title: "Tokyo Night",
    subtitle: "Cyberpunk Neon",
    desc: "Inspirado nas luzes noturnas de Tóquio com azul profundo e néon violeta",
    icon: "flash_on",
    category: "dark",
    isDark: true,
    colors: ["#7aa2f7", "#1a1b26", "#bb9af7"],
  },
  {
    id: "nord",
    title: "Nordic Frost",
    subtitle: "Ártico Minimalista",
    desc: "Paleta elegante com tons de azul gélido escuro e serenidade ártica",
    icon: "ac_unit",
    category: "dark",
    isDark: true,
    colors: ["#88c0d0", "#2e3440", "#81a1c1"],
  },
  {
    id: "matcha-forest",
    title: "Matcha & Forest",
    subtitle: "Verde Botânico",
    desc: "Verde esmeralda profundo e menta calmante para reduzir a fadiga mental",
    icon: "park",
    category: "dark",
    isDark: true,
    colors: ["#52b788", "#17231c", "#74c69d"],
  },
  {
    id: "rose-pine",
    title: "Rosé Pine",
    subtitle: "Estético & Macio",
    desc: "Mistura suave de pinho escuro, rosa pálido, dourado quente e lilás",
    icon: "spa",
    category: "dark",
    isDark: true,
    colors: ["#ebbcba", "#191724", "#f6c177"],
  },
  {
    id: "cyber-matrix",
    title: "Cyber Matrix",
    subtitle: "Hacker Terminal",
    desc: "Preto profundo com linhas e destaques em verde neon fosforescente",
    icon: "terminal",
    category: "dark",
    isDark: true,
    colors: ["#00ff88", "#080c0a", "#00cc6a"],
  },
];

export const THEME_IDS = THEMES.map((t) => t.id);

export function getThemeById(id) {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}

export function isDarkTheme(themeId, systemIsDark = false) {
  if (themeId === "system") return systemIsDark;
  const theme = getThemeById(themeId);
  return theme ? Boolean(theme.isDark) : false;
}
