export const SCREEN_IDS = {
  TODAY: "today",
  DASHBOARD: "dashboard",
  MODULES: "modules",
  FLASHCARDS: "flashcards",
  IMMERSION: "immersion",
  LESSON: "lesson",
  NOTES: "notes",
  NOTE_EDITOR: "note_editor",
  JOURNAL: "journal",
  CREATE_MODULE: "create_module",
  ADD_LESSON: "add_lesson",
  CREATE_FLASHCARDS: "create_flashcards",
  MODULE_DETAILS: "module_details",
  WORKSPACE: "workspace",
  WHITEBOARD: "whiteboard",
  CREATE_COURSE: "create_course",
  TASKS: "tasks",
  TASK_DETAILS: "task_details",
  PROJECTS: "projects",
  PROJECT_DETAILS: "project_details",
  POMODORO: "pomodoro",
  CODE_LAB: "code_lab",
  PROGRAMMING_PROJECT: "programming_project",
  ACADEMIC: "academic",
  DISCIPLINES: "disciplines",
  ACADEMIC_SUBJECT: "academic_subject",
  BOOKS: "books",
  BOOK_DETAILS: "book_details",
  BOOK_READER: "book_reader",
  SHARED: "shared",
  ACCOUNT: "account",
  KNOWLEDGE_HUB: "knowledge_hub",
  KNOWLEDGE_ITEM_DETAIL: "knowledge_item_detail",
};

export const SCREEN_ORDER = [
  SCREEN_IDS.DASHBOARD,
  SCREEN_IDS.MODULES,
  SCREEN_IDS.FLASHCARDS,
  SCREEN_IDS.IMMERSION,
];
