import { useState } from "react";
import { Icon } from "../ui/Icon";

export function ProgrammingProjectPanel({ programming = {}, onChange }) {
  const [milestone, setMilestone] = useState("");
  const [bug, setBug] = useState("");
  const update = (changes) => onChange({ ...programming, ...changes });
  const selectRepository = async () => {
    const selected = await window.studyhubDesktop?.selectDirectory?.();
    if (selected?.dirPath) update({ repositoryPath: selected.dirPath });
  };

  return <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
    <div className="space-y-6">
      <section className="rounded-[2rem] p-6 neo-raised"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[color:var(--primary)]">Ambiente do projeto</p><h2 className="mt-2 text-xl font-black">Stack e execução</h2></div><Icon name="terminal" className="text-3xl text-[color:var(--primary)]" /></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><ProjectField label="Linguagem"><input value={programming.language || ""} onChange={(event) => update({ language: event.target.value })} placeholder="C#, JavaScript, Python..." /></ProjectField><ProjectField label="Framework"><input value={programming.framework || ""} onChange={(event) => update({ framework: event.target.value })} placeholder=".NET, React, Django..." /></ProjectField><ProjectField label="Comando para executar"><input className="font-mono" value={programming.runCommand || ""} onChange={(event) => update({ runCommand: event.target.value })} placeholder="dotnet run" /></ProjectField><ProjectField label="Comando de testes"><input className="font-mono" value={programming.testCommand || ""} onChange={(event) => update({ testCommand: event.target.value })} placeholder="dotnet test" /></ProjectField></div><div className="mt-4"><ProjectField label="Pasta do repositório"><div className="flex gap-2"><input className="font-mono" value={programming.repositoryPath || ""} onChange={(event) => update({ repositoryPath: event.target.value })} placeholder="C:\\Projetos\\MeuProjeto" /><button onClick={selectRepository} className="rounded-xl px-4 text-sm font-black text-[color:var(--primary)] neo-inset"><Icon name="folder_open" /></button></div></ProjectField></div></section>
      <section className="rounded-[2rem] p-6 neo-raised"><p className="text-xs font-black uppercase tracking-[.16em] text-[color:var(--primary)]">Decisões técnicas</p><h2 className="mt-2 text-xl font-black">Arquitetura e aprendizados</h2><textarea className="mt-5 min-h-72 w-full rounded-2xl bg-[color:var(--background)] p-4 text-sm leading-7 outline-none neo-inset" value={programming.architectureNotes || ""} onChange={(event) => update({ architectureNotes: event.target.value })} placeholder="Estrutura de pastas, responsabilidades, dependências, decisões e motivos..." /></section>
    </div>
    <div className="space-y-6">
      <section className="rounded-[2rem] p-6 neo-raised"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[color:var(--primary)]">Roadmap técnico</p><h2 className="mt-2 text-xl font-black">Milestones</h2></div><span className="rounded-full px-3 py-1 text-xs font-black neo-inset">{(programming.milestones || []).filter((item) => item.completed).length}/{(programming.milestones || []).length}</span></div><div className="mt-5 space-y-2">{(programming.milestones || []).map((item) => <label key={item.id} className={`flex items-center gap-3 rounded-xl bg-[color:var(--background)] p-3 text-sm ${item.completed ? "opacity-55 line-through" : ""}`}><input type="checkbox" checked={item.completed} onChange={() => update({ milestones: programming.milestones.map((candidate) => candidate.id === item.id ? { ...candidate, completed: !candidate.completed } : candidate) })} /><span className="flex-1">{item.title}</span><button onClick={(event) => { event.preventDefault(); update({ milestones: programming.milestones.filter((candidate) => candidate.id !== item.id) }); }} className="text-[color:var(--on-surface-variant)] hover:text-red-500"><Icon name="close" className="text-base" /></button></label>)}</div><div className="mt-4 flex gap-2"><input value={milestone} onChange={(event) => setMilestone(event.target.value)} className="min-w-0 flex-1 rounded-xl bg-[color:var(--background)] px-3 py-2 text-sm outline-none neo-inset" placeholder="Nova entrega técnica" /><button onClick={() => { if (!milestone.trim()) return; update({ milestones: [...(programming.milestones || []), { id: `milestone-${Date.now()}`, title: milestone.trim(), completed: false }] }); setMilestone(""); }} className="rounded-xl px-3 text-[color:var(--primary)] neo-inset"><Icon name="add" /></button></div></section>
      <section className="rounded-[2rem] p-6 neo-raised"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-red-500">Diário de depuração</p><h2 className="mt-2 text-xl font-black">Bugs e bloqueios</h2></div><Icon name="bug_report" className="text-3xl text-red-500" /></div><div className="mt-5 space-y-3">{(programming.bugs || []).map((item) => <article key={item.id} className="rounded-xl bg-[color:var(--background)] p-4"><div className="flex items-center justify-between"><p className="text-sm font-black">{item.title}</p><button onClick={() => update({ bugs: programming.bugs.map((candidate) => candidate.id === item.id ? { ...candidate, resolved: !candidate.resolved } : candidate) })} className={`text-xs font-black ${item.resolved ? "text-green-600" : "text-red-500"}`}>{item.resolved ? "Resolvido" : "Aberto"}</button></div>{item.solution ? <p className="mt-2 text-xs leading-5 text-[color:var(--on-surface-variant)]">{item.solution}</p> : null}</article>)}</div><textarea value={bug} onChange={(event) => setBug(event.target.value)} className="mt-4 min-h-24 w-full rounded-xl bg-[color:var(--background)] p-3 text-sm outline-none neo-inset" placeholder="Descreva o erro, contexto e possível solução..." /><button onClick={() => { if (!bug.trim()) return; update({ bugs: [{ id: `bug-${Date.now()}`, title: bug.trim().split("\n")[0], solution: bug.trim(), resolved: false, createdAt: Date.now() }, ...(programming.bugs || [])] }); setBug(""); }} className="mt-3 rounded-xl bg-red-500 px-4 py-2 text-xs font-black text-white"><Icon name="add" /> Registrar bug</button></section>
    </div>
  </div>;
}

function ProjectField({ label, children }) { return <label className="block text-xs font-black uppercase tracking-wide text-[color:var(--on-surface-variant)]"><span>{label}</span><div className="mt-2 [&_input]:w-full [&_input]:rounded-xl [&_input]:bg-[color:var(--background)] [&_input]:px-3 [&_input]:py-2.5 [&_input]:text-sm [&_input]:outline-none [&_input]:shadow-[inset_2px_2px_5px_rgba(0,0,0,.06)]">{children}</div></label>; }
